{"time": 2023-10-15 19:28:24,963, "module": "app", "process": 58, "name": "app.py", "level": "INFO", "message": "Logger initialized."}
{"time": 2023-10-15 19:28:24,965, "module": "app", "process": 76, "name": "app.py", "level": "INFO", "message": "Backend server initialized."}
{"time": 2023-10-15 19:28:25,098, "module": "wasyncore", "process": 486, "name": "waitress", "level": "INFO", "message": "Serving on http://0.0.0.0:5000"}
{"time": 2023-10-15 19:29:32,941, "module": "app", "process": 58, "name": "app.py", "level": "INFO", "message": "Logger initialized."}
{"time": 2023-10-15 19:29:32,942, "module": "app", "process": 76, "name": "app.py", "level": "INFO", "message": "Backend server initialized."}
{"time": 2023-10-15 19:29:32,959, "module": "wasyncore", "process": 486, "name": "waitress", "level": "INFO", "message": "Serving on http://0.0.0.0:5000"}
{"time": 2023-10-15 19:29:37,400, "module": "app", "process": 825, "name": "app", "level": "ERROR", "message": "Exception on /send_graph [GET]"}
Traceback (most recent call last):
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/app.py", line 86, in send_graph
    df_monthly = pd.read_csv(
                 ^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../database/PVDAQ/monthly_aggregation/system_10_aggregation.csv'
{"time": 2023-10-15 19:29:37,401, "module": "app", "process": 825, "name": "app", "level": "ERROR", "message": "Exception on /system_metadata [GET]"}
Traceback (most recent call last):
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/app.py", line 126, in send_metadata
    df = pd.read_csv("../database/PVDAQ/metadata_deluxe.csv")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../database/PVDAQ/metadata_deluxe.csv'
{"time": 2023-10-15 19:29:58,003, "module": "app", "process": 825, "name": "app", "level": "ERROR", "message": "Exception on /send_graph [GET]"}
Traceback (most recent call last):
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/app.py", line 86, in send_graph
    df_monthly = pd.read_csv(
                 ^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../database/PVDAQ/monthly_aggregation/system_10_aggregation.csv'
{"time": 2023-10-15 19:29:58,008, "module": "app", "process": 825, "name": "app", "level": "ERROR", "message": "Exception on /system_metadata [GET]"}
Traceback (most recent call last):
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/app.py", line 126, in send_metadata
    df = pd.read_csv("../database/PVDAQ/metadata_deluxe.csv")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/mnt/B4C20210C201D78E/Travail/Projets perso/fullstocks_PV/backend/.venv/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../database/PVDAQ/metadata_deluxe.csv'
{"time": 2023-10-15 19:31:49,168, "module": "app", "process": 59, "name": "app.py", "level": "INFO", "message": "Logger initialized."}
{"time": 2023-10-15 19:31:49,169, "module": "app", "process": 77, "name": "app.py", "level": "INFO", "message": "Backend server initialized."}
{"time": 2023-10-15 19:31:49,187, "module": "wasyncore", "process": 486, "name": "waitress", "level": "INFO", "message": "Serving on http://0.0.0.0:5000"}
{"time": 2023-10-15 19:46:18,065, "module": "app", "process": 59, "name": "app.py", "level": "INFO", "message": "Logger initialized."}
{"time": 2023-10-15 19:46:18,066, "module": "app", "process": 77, "name": "app.py", "level": "INFO", "message": "Backend server initialized."}
{"time": 2023-10-15 19:46:18,081, "module": "wasyncore", "process": 486, "name": "waitress", "level": "INFO", "message": "Serving on http://0.0.0.0:5000"}
{"time": 2023-10-15 19:46:22,371, "module": "app", "process": 59, "name": "app.py", "level": "INFO", "message": "Logger initialized."}
{"time": 2023-10-15 19:46:22,372, "module": "app", "process": 77, "name": "app.py", "level": "INFO", "message": "Backend server initialized."}
{"time": 2023-10-15 19:46:22,387, "module": "wasyncore", "process": 486, "name": "waitress", "level": "INFO", "message": "Serving on http://0.0.0.0:5000"}
{"time": 2023-10-15 19:47:32,245, "module": "app", "process": 59, "name": "app.py", "level": "INFO", "message": "Logger initialized."}
{"time": 2023-10-15 19:47:32,246, "module": "app", "process": 77, "name": "app.py", "level": "INFO", "message": "Backend server initialized."}
{"time": 2023-10-15 19:47:32,260, "module": "wasyncore", "process": 486, "name": "waitress", "level": "INFO", "message": "Serving on http://172.17.0.1:5000"}
